# Generated by Django 5.1 on 2024-12-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adress2',
            new_name='address2',
        ),
    ]
